# Generated by Django 3.2 on 2021-04-24 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('otHours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemWallet',
            fields=[
                ('wallet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.wallet')),
                ('totalContributed', models.IntegerField()),
            ],
            bases=('api.wallet',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField(max_length=10)),
                ('availability', models.BooleanField()),
                ('item_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.itemwallet')),
            ],
        ),
    ]
